AWSTemplateFormatVersion: '2010-09-09'
Description: "Create the lambda functions"
Resources:
  ReviewMasterTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "username"
          AttributeType: "S"
        -
          AttributeName: "timestamp"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "username"
          KeyType: "HASH"
        -
          AttributeName: "timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
Outputs:
  DBTableName:
    Description: "Dyanamo DB Table name for ReviewMaster"
    Value: !Ref ReviewMasterTable
    Export:
      Name: "DB-TableName"
