AWSTemplateFormatVersion: '2010-09-09'
Description: "Create the EC2webserver instance"
Parameters:
  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "EC2 KeyPair Name"
Resources:
  PublicInstSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow http and ssh to webservers"
      VpcId: !ImportValue "RMVPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-a4c7edb2"
      InstanceType: "t2.micro"
      KeyName:
        Ref: "EC2KeyPair"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref "PublicInstSecGroup"
          SubnetId: !ImportValue "RMPublicSNID"
